services:
  # Web 服务（基于您的 Dockerfile 构建）
  # web:
  #   build:
  #     context: . # 使用当前目录下的 Dockerfile
  #     dockerfile: Dockerfile # 指定 Dockerfile 路径
  #   container_name: news-summary-web # 自定义容器名称
  #   volumes:
  #     - .:/news-summary:z # 确保和 Dockerfile 里的 WORKDIR 一致
  #     - /news-summary/.venv # 避免覆盖 .venv, 开发环境必须要设置
  #   ports:
  #     - "8000:8000" # 暴露 FastAPI 端口
  #   env_file:
  #     - .env # 加载环境变量
  #   depends_on:
  #     - db
  #     # - redis
  #   networks:
  #     - app-network

  # 数据库服务
  db:
    image: postgres:13
    container_name: news-summary-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # 将宿主机的 5432 端口映射到容器的 5432 端口
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d newsdb"]
      interval: 2s
      timeout: 2s
      retries: 3
    networks:
      - otel-net

  test-db:
    image: postgres:13
    container_name: news-summary-db-test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_newsdb
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # 将宿主机的 5433 端口映射到容器的 5432 端口
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_newsdb"]
      interval: 2s
      timeout: 2s
      retries: 3
    networks:
      - otel-net

  # Redis 服务
  # redis:
  #   image: redis:6
  #   container_name: news-summary-redis
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - app-network

  # Celery 服务
  # celery:
  #   build:
  #     context: . # 使用与 web 相同的 Dockerfile
  #     dockerfile: Dockerfile
  #   container_name: news-summary-celery
  #   command: celery -A app.tasks.celery_app worker --loglevel=info
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - app-network

  # Sentry 服务
  # sentry:
  #   image: sentry:latest
  #   container_name: news-summary-sentry
  #   depends_on:
  #     - sentry-postgres
  #     - sentry-redis
  #   environment:
  #     SENTRY_SECRET_KEY: "your-sentry-secret-key"
  #     SENTRY_POSTGRES_HOST: sentry-postgres
  #     SENTRY_DB_USER: sentry
  #     SENTRY_DB_PASSWORD: sentry
  #     SENTRY_DB_NAME: sentry
  #     SENTRY_REDIS_HOST: sentry-redis
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - app-network
  #   command: |
  #     bash -c "
  #     sentry upgrade --noinput &&
  #     sentry run web"

  # Sentry 的 PostgreSQL 数据库
  # sentry-postgres:
  #   image: postgres:13
  #   container_name: news-summary-sentry-postgres
  #   environment:
  #     POSTGRES_USER: sentry
  #     POSTGRES_PASSWORD: sentry
  #     POSTGRES_DB: sentry
  #   volumes:
  #     - sentry_postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  # Sentry 的 Redis
  # sentry-redis:
  #   image: redis:6
  #   container_name: news-summary-sentry-redis
  #   volumes:
  #     - sentry_redis_data:/data
  #   networks:
  #     - app-network

  # Grafana 服务
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - otel-collector
      - prometheus
      - tempo
      - loki
    networks:
      - otel-net

  # otel 服务
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel/otel.yaml"]
    volumes:
      - ./config/otel/otel.yaml:/etc/otel/otel.yaml
    ports:
      - "4317:4317" # gRPC OTLP
      - "9464:9464" # Prometheus Metrics
    networks:
      - otel-net

  # Tempo 服务
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200" # Tempo HTTP API
    networks:
      - otel-net

  # Prometheus 服务
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    networks:
      - otel-net

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    volumes:
      # 这里注释掉，用默认的配置
      # - ./config/loki/loki.yaml:/etc/loki/config.yaml
      - loki_data:/tmp/loki
    ports:
      - "3100:3100"
    networks:
      - otel-net

# 定义卷
volumes:
  postgres_data:
  postgres_test_data:
  grafana_data:
  tempo_data:
  loki_data:
  # redis_data:
  # sentry_postgres_data:
  # sentry_redis_data:

# 定义网络
networks:
  otel-net:
    driver: bridge
