name: Deploy

# on: [push, pull_request]
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_USER: root
      REMOTE_DEPLOY_DIR: /root/opt/rss/backend/deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create archive code
        run: |
          mkdir deploy
          rsync -av --exclude=deploy . deploy/
          cp .env deploy/
          tar -czf build.tar.gz -C deploy .

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.REMOTE_IP }} >> ~/.ssh/known_hosts

      - name: Upload and extract, then Run
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@${{ secrets.REMOTE_IP }} "mkdir -p $REMOTE_DEPLOY_DIR"
          scp -o StrictHostKeyChecking=no build.tar.gz $REMOTE_USER@${{ secrets.REMOTE_IP }}:$REMOTE_DEPLOY_DIR/
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@${{ secrets.REMOTE_IP }} "cd $REMOTE_DEPLOY_DIR && tar -xzf build.tar.gz && rm build.tar.gz"
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@${{ secrets.REMOTE_IP }} "cd $REMOTE_DEPLOY_DIR && make docker-run"
