name: Deploy

# on: [push, pull_request]
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_USER: root
      REMOTE_DEPLOY_DIR: /root/deploy/backend

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v3

      - name: 🕵️ Debug workspace
        run: ls -al && du -sh *

      - name: 📤 Copy project files to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "${{ env.REMOTE_DEPLOY_DIR }}"
          strip_components: 0

      - name: 📄 Create .env file and Copy .env to server via SCP
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: 📤 Copy .env to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: "${{ env.REMOTE_DEPLOY_DIR }}"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@${{ secrets.REMOTE_IP }} <<EOF
            cd $REMOTE_DEPLOY_DIR
            make docker-run
          EOF
